events {}

http {
  server {
    listen 80;

    location / {
      root /usr/share/nginx/html;
      index index.html;
    }

    location /todos {
      proxy_pass http://todo-backend:4000/todos;
    }
  }
}
