version: "3.9"
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    # ネットワーク設定を追加
    networks:
      - app-network

  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "4000:4000"
    depends_on:
      - db
    # ネットワーク設定を追加
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: todo-db
    env_file:
      - .env.db
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    # ネットワーク設定を追加
    networks:
      - app-network

# ネットワークを定義
networks:
  app-network:
    driver: bridge

volumes:
  db-data: