services:
  db:
    image: mysql:8.0
    container_name: todo-mysql
    command:
      - 'mysqld'
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
    restart: always
    env_file:
      - .env.db
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    container_name: todo-backend
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/usr/share/nginx/html
    container_name: todo-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
